name: Ping Strapi

on:
  schedule:
    # - cron: '*/1 * * * *'  # Runs every 1 minute
    # - cron: '*/3 * * * *' # Runs every 3 minutes
    # - cron: '*/15 * * * *' # Runs every 15 minutes
    - cron: '0 0 1 * *'  # Runs at 00:00 on the 1st day of every month

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Strapi
        run: curl -I https://murshed-api.onrender.com
