name: Ping Strapi

on:
  schedule:
    - cron: '*/15 * * * *' # Runs every 15 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Strapi
        run: curl -I https://murshed-api.onrender.com
